import UnderDevelopment from "@/components/UnderDevelopment";
import "./globals.css";
import Navbar from "@/components/navbar";



export const metadata = {
	title: 'Al-Huda',
	description: 'Generated by create next app',
	icons: {
		icon: '/logo/hiddeneye-logo.png',
	},
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
        <Navbar />
        <UnderDevelopment />
        <UnderDevelopment />
        <UnderDevelopment />
        <UnderDevelopment />
        {children}
      </body>
    </html>
  );
}
